### ISSUE TITLE
Weather.py crashes with TypeError

### ISSUE THREAD

**Issue by g7vkq** [chrissyhroberts/badger2040w_code#4]
Weather.py crashes with TypeError: unsupported types for __gt__: 'NoneType', 'float'

The failing line is 81:

uv_index = max(airquality["uv_index"])

Stack trace and part of Air Quality data structure attached
<img width="1194" alt="Screenshot 2023-08-16 at 09 58 05" src="https://github.com/chrissyhroberts/badger2040w_code/assets/22982772/464ebb68-9d20-4f47-8e92-67fde95cc37e">
[Air Quality.txt](https://github.com/chrissyhroberts/badger2040w_code/files/12357683/Air.Quality.txt)

**Comment by g7vkq** [comment]
Second part of Air Quality data structure (with UV Index data). Apologies for not attaching to original comment

[Air Quality2.txt](https://github.com/chrissyhroberts/badger2040w_code/files/12357722/Air.Quality2.txt)

**Comment by chrissyhroberts** [comment]
release v0.01 fixes this issue, which was caused by empty values in the scraped data. There’s changes throughout the text which address the potential that this could happen elsewhere. Hopefully fixed. To test, please download and flash the latest release to your badger device

**Comment by g7vkq** [comment]
That's perfect and solved the problem completely! Thanks for this great little app
